"""empty message

Revision ID: 01dd5cf24c6b
Revises: 
Create Date: 2023-12-08 17:16:20.959280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01dd5cf24c6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('discord_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Users'))
    )
    op.create_table('Tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('game', sa.String(), nullable=True),
    sa.Column('format', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['Users.id'], name=op.f('fk_Tournaments_creator_Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Tournaments'))
    )
    op.create_table('Entrants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('discord_id', sa.Integer(), nullable=True),
    sa.Column('point_total', sa.Integer(), nullable=True),
    sa.Column('opponents', sa.String(), nullable=True),
    sa.Column('dropped', sa.Boolean(), nullable=True),
    sa.Column('pair_up_down', sa.Boolean(), nullable=True),
    sa.Column('bye', sa.Boolean(), nullable=True),
    sa.Column('SOS', sa.Float(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['Tournaments.id'], name=op.f('fk_Entrants_tournament_id_Tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Entrants'))
    )
    op.create_table('Matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('tournament', sa.Integer(), nullable=True),
    sa.Column('player_1_id', sa.Integer(), nullable=True),
    sa.Column('player_2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_1_id'], ['Entrants.id'], name=op.f('fk_Matches_player_1_id_Entrants')),
    sa.ForeignKeyConstraint(['player_2_id'], ['Entrants.id'], name=op.f('fk_Matches_player_2_id_Entrants')),
    sa.ForeignKeyConstraint(['tournament'], ['Tournaments.id'], name=op.f('fk_Matches_tournament_Tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Matches'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Matches')
    op.drop_table('Entrants')
    op.drop_table('Tournaments')
    op.drop_table('Users')
    # ### end Alembic commands ###
