"""empty message

Revision ID: 16391a4bd7ec
Revises: f22bd78277a0
Create Date: 2023-11-07 15:56:04.273450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16391a4bd7ec'
down_revision = 'f22bd78277a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
