"""empty message

Revision ID: 56af5d84b8c3
Revises: 6981c714e50a
Create Date: 2023-11-14 16:39:48.568404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56af5d84b8c3'
down_revision = '6981c714e50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entrants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dropped', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pair_up_down', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bye', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entrants', schema=None) as batch_op:
        batch_op.drop_column('bye')
        batch_op.drop_column('pair_up_down')
        batch_op.drop_column('dropped')

    # ### end Alembic commands ###
