"""empty message

Revision ID: 6185268413b3
Revises: 30158a68c0ac
Create Date: 2023-11-20 14:30:58.927203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6185268413b3'
down_revision = '30158a68c0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entrants', schema=None) as batch_op:
        batch_op.alter_column('opponents',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entrants', schema=None) as batch_op:
        batch_op.alter_column('opponents',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
