"""empty message

Revision ID: 6981c714e50a
Revises: d65b05bd452a
Create Date: 2023-11-07 16:09:26.206489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6981c714e50a'
down_revision = 'd65b05bd452a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entrants', schema=None) as batch_op:
        batch_op.alter_column('point_total',
               existing_type=sa.INTEGER(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entrants', schema=None) as batch_op:
        batch_op.alter_column('point_total',
               existing_type=sa.BLOB(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
