"""empty message

Revision ID: d65b05bd452a
Revises: 16391a4bd7ec
Create Date: 2023-11-07 16:05:36.867491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65b05bd452a'
down_revision = '16391a4bd7ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entrants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))

    with op.batch_alter_table('Tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tournaments', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('Entrants', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
