"""empty message

Revision ID: e8255e9fbf04
Revises: 2f7664a3dece
Create Date: 2023-11-28 20:59:56.005175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8255e9fbf04'
down_revision = '2f7664a3dece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entrants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entrants', schema=None) as batch_op:
        batch_op.drop_column('discord_id')

    # ### end Alembic commands ###
