"""empty message

Revision ID: f22bd78277a0
Revises: 1313cf8eecf2
Create Date: 2023-11-07 15:52:16.437913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22bd78277a0'
down_revision = '1313cf8eecf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('game', sa.String(), nullable=True),
    sa.Column('format', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['Users.id'], name=op.f('fk_Tournaments_creator_Users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Tournaments'))
    )
    op.create_table('Entrants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_total', sa.Integer(), nullable=True),
    sa.Column('opponents', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['Tournaments.id'], name=op.f('fk_Entrants_tournament_id_Tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Entrants'))
    )
    op.create_table('Matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('tournament', sa.Integer(), nullable=True),
    sa.Column('player_1', sa.Integer(), nullable=True),
    sa.Column('player_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_1'], ['Users.id'], name=op.f('fk_Matches_player_1_Users')),
    sa.ForeignKeyConstraint(['player_2'], ['Users.id'], name=op.f('fk_Matches_player_2_Users')),
    sa.ForeignKeyConstraint(['tournament'], ['Tournaments.id'], name=op.f('fk_Matches_tournament_Tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Matches'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Matches')
    op.drop_table('Entrants')
    op.drop_table('Tournaments')
    # ### end Alembic commands ###
